name: fast_geohash_example
description: "Example project showing a map and geohashes on it"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  fast_geohash:
    path: ../
  flutter_map: ^8.2.2
  latlong2: ^0.9.1

dev_dependencies:
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true